"""
main.py — FastAPI application entry point.

Start the server:
    uvicorn backend.main:app --reload

Interactive API docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs      ← Swagger UI
    http://127.0.0.1:8000/redoc     ← ReDoc
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from backend.api.routes import router

app = FastAPI(
    title="Personal RAG API",
    description="Advanced RAG system over Jay Zhang's personal knowledge base.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)


@app.get("/health")
async def health() -> dict:
    return {"status": "ok"}
